@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyLTAwMSIsImVtYWlsIjoicXdlIiwiZnVsbG5hbWUiOiJxd2UgcXdlIiwiaWF0IjoxNjkyOTY0NDIzfQ.ZWf1uc9zp5rOyEfexI8RlLhbbeaM8o5FZ7j6GDLeCyA

POST http://127.0.0.1:5001/api/note HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "type" : "personal",
    "note" : "dummy data will delete soon 001"
}

###
GET http://127.0.0.1:5001/api/note HTTP/1.1
Authorization: {{token}}

###
GET http://127.0.0.1:5001/api/note/3 HTTP/1.1
Authorization: {{token}}

###
PUT http://127.0.0.1:5001/api/note/3 HTTP/1.1
content-type: application/json
Authorization: {{token}}

{
    "note" : "update note"
}

###
DELETE  http://127.0.0.1:5001/api/note/3 HTTP/1.1
content-type: application/json
Authorization: {{token}}