POST http://127.0.0.1:5001/api/user HTTP/1.1
content-type: application/json

{
    "username" : "user-001",
    "first_name" : "qwe",
    "last_name" : "qwe",
    "email" : "qwe",
    "password" : "123123123",
    "gender" : "Male",
    "date_of_birth" : "2023-08-11"
}

###

POST http://127.0.0.1:5001/api/login HTTP/1.1
content-type: application/json

{
    "username" : "user-001",
    "password" : "123123123"
}


###
GET http://127.0.0.1:5001/api/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJ1c2VyLTAwMSIsImVtYWlsIjoicXdlIiwiZnVsbG5hbWUiOiJxd2UgdW5kZWZpbmVkIiwiaWF0IjoxNjkyOTE4MjYyfQ.xxH89ezSU4A9PMfm9tUG8tjPby18u3PvV8XkRHAizLw